### ISSUE TITLE
Difficulty assessment of rav1e-wasm project

### ISSUE THREAD

**Issue by Urhengulas** [mozilla/GSOC2020#67]
Hello Mozillians, friends of Mozilla and fellow students interested in GSoC2020,
(I guess @negge might be able to answer my question)

As the headline says this is about the [rav1e-wasm project](https://github.com/mozilla/GSOC2020/blob/master/proposals/rav1e-wasm.md).

---

The proposal states:
```markdown
An applicant needs:
* Rust knowledge
* WebAssembly knowledge
* x86_64 or Aarch64 SIMD extensions
* JavaScript knowledge (preferred)
```

My question is if my skills are sufficient for the task:
* **Rust:** I played around with Rust in the past and am very willing to learn it properly. Despite I know from some of my friends that Rust has a stepp learning curve I am sure that I can wrap my head around it and build on top of my well-founded knowledge in golang, typescript, and python.
* **WebAssembly:** In the last couple of weeks a got a bit hyped about webassembly, read many docs in the mdn about it and played around with AssemblyScript as well as Building wasm-modules with golang
* **JavaScript:** good typescript, node and react knowledge

---

Resulting in the question:
**Do you think my current skills + willingness to develop are adequate to pick this challenge?**

Thanks in advance to everyone taking the time to read and/or answer :)

**Comment by negge** [comment]
Hello, yes I may be the best person to answer.

This GSoC project is primarily around improving the performance of WebAssembly based video encoding using rav1e.  There are already a few people who are experimenting with the wasm32-wasi build target in the rav1e project directly and we know complexity could be reduced with WASM.SIMD.

The technical gap that needs to be addressed is that [rav1e](http://github.com/xiph/rav1e) imports much of it's SIMD assembly from the [dav1d](https://code.videolan.org/videolan/dav1d) project, where this code has been hand written for a variety of targets (SSE2, SSSE3, SSE4, AVX2, AVX512, NEON, etc.).  This is good as it gives us considerable performance when rav1e is built for those targets.  Unfortunately, there is no _transpiler_ from the Intel x86 syntax used by nasm-rs to WebAssembly, let alone WASM.SIMD.

The initial set of tasks are to build and profile rav1e under wasm32-wasi, identify the DSP functions with the worst performance, and then use the built in Rust SIMD extensions with a WASM target so that the llvm backend will emit WASM.SIMD.  Our expectation is that doing this for a handful of functions will dramatically improve the performance.

This means that in addition to understanding the three technologies you listed above, having experience with SIMD assembly and intrinsics is highly desired.  Also, because the WASM.SIMD standard is not finalized, there is an opportunity to feed back learnings from this real world application and ensure the right mnemonics are exposed.  Certainly, knowing how to do the WebAssembly and JS integration will be useful for setting up a test page to demonstrate the performance improvements.

As briefly identified in the [Project Description](https://github.com/mozilla/GSOC2020/blob/master/proposals/rav1e-wasm.md), there are other things that can be done to improve wasm32-wasi performance, including work on the [rayon](https://github.com/rayon-rs/rayon) multi-threading library and how it integrates with WebAssembly workers.  Because we are very early in targeting wasm32-wasi with rav1e, there are many ways to contribute to the project.

Please let me know if you have any further questions.

**Comment by Urhengulas** [comment]
Thanks for your fast reply!

Now the project sounds even more interesting to me. I am going to read up on the information you send and am going to compile a proposal asap.

**Comment by negge** [comment]
Glad I could help.  Feel free to ask if you have other questions.

**Comment by Urhengulas** [comment]
Will do :)
Going to close this issue for now
